name: "Cover Art Archive"
guid: "8119f3c6-cfc2-4d9c-a0ba-028f1d93e526"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-coverartarchive.png"
version: 9
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "MusicBrainz Cover Art Archive"
description: >
  This plugin provides images from the Cover Art Archive https://musicbrainz.org/doc/Cover_Art_Archive and depends on the MusicBrainz metadata provider to know what images belong where

category: "Music"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.CoverArtArchive.dll"
  - "MetaBrainz.Common.Json.dll"
  - "MetaBrainz.MusicBrainz.CoverArt.dll"
changelog: |-
  - Jellyfin 10.11 support (#39) @crobibero
